### ISSUE TITLE
Slider behavior on iOS app

### ISSUE THREAD

**Issue by calvinmaniac12** [thomasloven/lovelace-slider-entity-row#85] opened 2019-11-29 07:57 UTC
I love this add on, but I have had to phase it out of my build because of the way the sliders function on iOS app. Unlike the input_slider or the brightness slider on the Lovelace Light Card, you do _not_ have to click on the slider button and drag to the desired brightness. Instead, the slider will switch to a new value if you click anywhere on the slider bar. This has created a lot of issues on iOS, because when scrolling down a page or through my interface, I will accidentally turn on lights all over the place just by simply tapping on one of the slider bars (at a location different than the slider 'pin'). Finding a way to fix this behavior of the bar (making it similar in function the the actual input_slider), would make it much more usable for iOS and other touchscreen devices reliant on any type of sliding or swiping to navigate the UI.

**Comment by thomasloven** [comment] 2019-11-29 11:14
Duplicate of #54, which was recently fixed?

Is this really an issue with the latest release titled "Fix scrolling on mobile"?

**Comment by calvinmaniac12** [comment] 2019-11-29 18:39
I'm not sure I know what you are referencing by "Fix scrolling on mobile"...can you clarify?

I can confirm that this issue is _not_ fixed by what is discussed in #54. I have updated the entire component, and I see the changes made in the lightcontroller.js and main.js on my end as changed in f9064d6.

**Comment by thermseekr** [comment] 2019-11-29 20:48
Release 10 addresses this exact issue. I have it installed and working very
well.


Em sex., 29 de nov. de 2019 às 15:39, Ryan Clodfelter <
notifications@github.com> escreveu:

**Comment by calvinmaniac12** [comment] 2019-11-29 22:03
Hmm I have release 10. If I have a slider active on a page on iOS and happen to click on part of the slider (_not_ the part with the dragging circle), it will still set the light brightness. I'm not sure what I'm doing wrong, because I have confirmed that I have Release 10, the most recent pull of Hass, and have restarted my system a few times.

**Comment by thermseekr** [comment] 2019-11-30 09:34
Ha, if you click on it (touch and lift your finger) it should really assume the new position. This is expected behavior, allows you to set brightness/volume/whatever without needing to drag it. What release 10 does is that it no longer actuates the slider when you touch it while scrolling the page.

Enviado do meu iPhone

**Comment by thomasloven** [comment] 2019-12-01 19:13
Indeed.
Clicking/tapping the bar to change the position of a slider is exactly the same as with the default slider, and release 10 fixes the problem with accidentally changing the position while scrolling, which I believe was your actual problem?

**Closed** 2020-05-13 20:07 UTC
