### ISSUE TITLE
Issue with header toggle on entities card

### ISSUE THREAD

**Issue by KungFuJoe23** [thomasloven/lovelace-slider-entity-row#157] opened 2020-10-12 07:48 UTC
When configuring an entities card in lovelace and then modifying entities to use the slider-entity-row feature, the group toggle doesn't affect any entities using slider-entity-row.

Any entities in the group that don't use slider-entity-row all toggle on/off when I toggle the group, as expected.

Not sure exactly when this stopped working.  I'm on 0.116.2 and I imagine this was very recent as I use this feature often.

**Comment by seagri** [comment] 2020-10-12 08:11
Same for me. I went from 0115.6 yesterday and I'm pretty sure it worked then.

In this picture the group toggle is off but the slider-lamp is still on
![image](https://user-images.githubusercontent.com/12122654/95721594-1f401d80-0c73-11eb-87f0-72324b48bb15.png)

**Comment by thomasloven** [comment] 2020-10-12 08:32
Duplicate of **pinned** issue #155

**Closed by thomasloven** 2020-10-12 08:32 UTC
