### ISSUE TITLE
Add ability to include transition. 

### ISSUE THREAD

**Issue by JustTheLogan** [thomasloven/lovelace-slider-entity-row#251] opened 2022-05-23 11:17 UTC
Currently, most used hacs card. What would be fantastic is the ability to allow a transition setting to be implemented into the code for the slider. New to hacs and wondering if this is a feature for the slide? Like the switch or (toggle: true) button currently integrated with lifx bulbs will fade on and off by default. This can also not be changed. 

Loving the card!

**Comment by thomasloven** [comment] 2022-05-25 11:03
Duplicate of #238

**Closed by thomasloven** 2022-05-25 11:03 UTC
