### ISSUE TITLE
Layout issue with Home Assistant 0.107 and small screen (tablet)

### ISSUE THREAD

**Issue by earion68** [thomasloven/lovelace-slider-entity-row#98] opened 2020-03-19 13:39 UTC
Since upgrading to Home Assistant 0.107.1 the display is going wrong with small screens (such as a tablet in kiosk mode) and the slider overlaps the other columns.

![image](https://user-images.githubusercontent.com/54678154/77073315-5e650380-69ef-11ea-9e5f-6bcc47b215da.png)

**Comment by basnijholt** [comment] 2020-03-19 14:43
Also reported in https://github.com/thomasloven/lovelace-slider-entity-row/issues/97.

**Comment by epiller** [comment] 2020-03-19 22:57
Same here! 
P.S. @earion68 Beautiful dashboard you have there!

**Comment by Jurgenn22** [comment] 2020-03-20 17:28
Same here, in multiple browsers same issue (Mac OS Safari, Google Chrome)

![slider](https://user-images.githubusercontent.com/50082445/77189866-8c724280-6ad8-11ea-87cd-62ec34f7a58f.jpeg)

**Comment by Jurgenn22** [comment] 2020-03-20 20:18
This works for me. Just trying, I'm not a developer by far. 
![new config](https://user-images.githubusercontent.com/50082445/77203200-2396c480-6af0-11ea-8cf3-b8f6e13a8814.jpeg)
![slider](https://user-images.githubusercontent.com/50082445/77203208-298ca580-6af0-11ea-9afd-6f72c419555f.jpeg)

**Comment by earion68** [comment] 2020-03-21 08:54
Thanks for the workaround!

**Comment by jaydouble** [comment] 2020-03-21 09:07
Same here, this is seriously bad for the WAF...

**Comment by rgruyters** [comment] 2020-03-21 11:01
Yep same issue here. 

<img width="340" alt="Screenshot 2020-03-21 at 12 00 24" src="https://user-images.githubusercontent.com/2082795/77225026-a1e47c80-6b6b-11ea-9369-0e154d7d22c2.png">

**Comment by GaryOkie** [comment] 2020-03-21 18:15
I really appreciate that you posted a workaround @Jurgenn22!       Limiting the size of the slider was exactly what I was looking into and your post saved me quite a bit of time of CSS trial and error.

**Comment by Jurgenn22** [comment] 2020-03-21 18:50
Your welcome @GaryOkie! Thx for the "insert code" edit, I did not know that.

**Comment by t9001** [comment] 2020-03-22 20:50
Great workaround, thanks @Jurgenn22 !
I get good results across different devices by using a %, your mileage may vary...
`type: 'custom:slider-entity-row'
    style: |
      div {
        max-width: 60%;
        margin: auto;
      }`

**Comment by Mariusthvdb** [comment] 2020-03-23 22:08
dont think a 'hack' in Style should be necessary, nor as per design by Thomas. Giving as much to go on to debug this:

using:
```
  - type: entities
    title: Philips Hue lights
    show_header_toggle: true
    entities:
      - type: custom:slider-entity-row
        entity: light.backdoor_outdoors
      - type: custom:slider-entity-row
        entity: light.gate_outdoors
      - type: custom:slider-entity-row
        entity: light.porch_outdoors
      - type: custom:slider-entity-row
        entity: light.laundry_ceiling
      - type: custom:slider-entity-row
        entity: light.silver_cabinet
        toggle: true
        hide_when_off: true
      - type: custom:slider-entity-row
        entity: light.dining_corner
        toggle: true
        hide_when_off: true
      - type: custom:slider-entity-row
        entity: light.dining_table_lamp_1
        toggle: true
      - type: custom:slider-entity-row
        toggle: true
        entity: light.dining_table_lamp_2
      - type: custom:slider-entity-row
        toggle: true
        entity: light.dining_table_lamp_3
```

resulting in:

<img width="429" alt="Schermafbeelding 2020-03-23 om 23 02 57" src="https://user-images.githubusercontent.com/33354141/77367754-18939c80-6d5b-11ea-8850-72e1cea9c7fe.png">

on Ha 107.5 and current slider-entity-row 11

**Comment by Jurgenn22** [comment] 2020-03-24 19:30
Your welcome @t9001 .

**Comment by sentinel43** [comment] 2020-04-02 11:23
Is this going to be fixed soon? I am trying to manually edit and change some lines according to given links but there is no success and this is so annoying.  Thanks in advance.

**Comment by GaryOkie** [comment] 2020-04-02 13:36
> Is this going to be fixed soon?

Did you not see the post immediately above yours?    A PR to fix the slider was committed 5 days ago and if you update slider-entity-row it should be working fine now.   I just removed all the workaround style hacks and confirmed it is back to normal now.

**Comment by basnijholt** [comment] 2020-04-02 13:41
I guess @thomasloven, should release a new version for it to properly propagate to most people (using HACS).

**Comment by Jurgenn22** [comment] 2020-04-02 14:44
@GaryOkie 
Hello,
The latest fix from 4 days ago, version 11, did not fix it, for me unfortunately.

**Comment by GaryOkie** [comment] 2020-04-02 14:52
Yeah, after posting, I had only tested it on my laptop and tablet, and it seemed to work ok.   Just now tested on small screen mobile and no text.     #101 should hopefully solve it.

**Comment by Jurgenn22** [comment] 2020-04-02 14:55
@GaryOkie 
On my macbook with safari and with google chrome, same as before, slider goes outside the card.

**Comment by eggman0131** [comment] 2020-04-03 09:33
Another card-mod workaround, no idea if it's better or worse that previous proposals.  It retains full alignment with any 'standard' entity rows I have in the same card and prevents slider-entity-row from going off the side, unless the entity card is ridiculously narrow (at which point standard entity rows also go off the side).

Add the following style to the card

```
    style:
      "#states div":
        slider-entity-row:
          $:
            hui-generic-entity-row: |
              .wrapper {
                display: contents !important;
              }  
```

**Comment by GaryOkie** [comment] 2020-04-03 14:14
I tried your style mod but it didn't really help.   @t9001 's max-width % mod is working the best for me on a mobile.

**Comment by eggman0131** [comment] 2020-04-04 06:19
> I tried your style mod but it didn't really help. @t9001 's max-width % mod is working the best for me on a mobile.

OK, works perfectly for me on all my screen sizes, but YMMV

**Comment by anrada73** [comment] 2020-04-04 15:53
all tips do not work

**Comment by ntompson** [comment] 2020-04-06 07:19
Adding to those who have discovered this issue. For me, happens in all browsers I am using on macOS (chrome and Safari) but completely fine on the iOS app. Ironically, the workaround (60% max width) makes the layout on the iOS app slightly worse (switch slightly out of alignment on right hand side).

**Closed** 2020-04-14 20:13 UTC

**Comment by jeffchampagne** [comment] 2020-04-14 21:13
Working much better now with 0a420fe thanks!
